dist: bionic

language: python

python:
  - "3.7"
  - "3.8"

services:
  - docker

cache:
  directories:
    - "$HOME/.npm"

before_install:
  - npm install

install:
  - curl -sSL https://cli.openfaas.com | sudo -E sh
  - pip install -U pip
  - pip install -r time_operator/dev_requirements.txt
  - pip install -r time_operator/requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - flake8 time_operator/
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: security
      script:
        - bandit -r time_operator -x time_operator/test_handler.py
    - stage: build_dev
      if: branch = develop
      script:
        - faas-cli template pull
        - faas-cli build -f time_operator.yml --build-arg ADDITIONAL_PACKAGE="python3-dev libstdc++ g++" --tag describe
    - stage: build_prod
      if: branch = master
      script:
        - faas-cli template pull
        - faas-cli build -f time_operator.yml --build-arg ADDITIONAL_PACKAGE="python3-dev libstdc++ g++"
    - stage: deploy_image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - faas-cli push -f time_operator.yml


script:
  - export PYTHONPATH=$(pwd)
  - pytest time_operator/
  - pytest --cov=time_operator time_operator/
  - pytest --cov=time_operator --cov-report xml time_operator/
  - unset PYTHONPATH
